export const MAX_CACHE_SIZE = 300;
export const INSTAGRAM_LINK = "https://www.instagram.com/sipnplaynyc/?hl=en";
export const FACEBOOK_LINK = "https://www.facebook.com/sipnplaynyc/";

export const BOARD_GAMES = [
  { name: "13 Days" },
  { name: "Apples to Apples" },
  { name: "Patchwork" },
  { name: "Arkham Horror LCG" },
  { name: "20 second showdown" },
  { name: "5 Second Rule" },
  { name: "Onitama" },
  { name: "Spirit Island" },
  { name: "221B Baker Street" },
  { name: "Codenames" },
  { name: "7 Wonders: Duel" },
  { name: "Stone Age" },
  { name: "5 Second Rule: Jr." },
  { name: "Sequence" },
  { name: "Villainous" },
  { name: "Roll for the Galaxy" },
  { name: "5 Second Rule: Uncensored" },
  { name: "Monopoly" },
  { name: "Memoir 44" },
  { name: "Agricola" },
  { name: "5-Minute Dungeon" },
  { name: "5-Minute MARVEL" },
  { name: "7 Wonders" },
  { name: "8 Minute Empire: Legends" },
  { name: "8 Minute Empire: Lost Lands" },
  { name: "A Game of Thrones: The Board Game" },
  { name: "Above and Below" },
  { name: "Acquire" },
  { name: "Agricola" },
  { name: "Apples to Apples" },
  { name: "Ascension Deck Building Game" },
  { name: "Attack of the killer kittens" },
  { name: "Attack of the killer kittens (NSFW)" },
  { name: "Axis & Allies: Pacific" },
  { name: "Azul: Stained glass of Sintra" },
  { name: "Badmoji" },
  { name: "Bananagrams" },
  { name: "Bang!" },
  { name: "Bang! Dice Expansion: Old Saloon" },
  { name: "Bang! The Dice Game" },
  { name: "Barenpark" },
  { name: "Battle for the island" },
  { name: "Battleline" },
  { name: "Battleship" },
  { name: "Betrayal at House on the Hill" },
  { name: "Big Boggle" },
  { name: "Blockbuster" },
  { name: "Blokus" },
  { name: "Blood Rage" },
  { name: "Boggle" },
  { name: "Brain Games" },
  { name: "Broom Service" },
  { name: "CAH Expansions 1-4,6" },
  { name: "Camel Cup" },
  { name: "Captain Sonar" },
  { name: "Carcassonne" },
  { name: "Cards Against Humanity" },
  { name: "Cash 'n Guns" },
  { name: "Castle Panic" },
  { name: "Catan Expansion: Seafarers" },
  { name: "Catan Junior" },
  { name: "Chameleon" },
  { name: "Cheating Moth" },
  { name: "Checkers" },
  { name: "Cheer up!" },
  { name: "Chess" },
  { name: "Chicago Express" },
  { name: "Chinese Checkers" },
  { name: "Chronoauts" },
  { name: "Chronology" },
  { name: "Chutes & Ladders" },
  { name: "Citadels" },
  { name: "City of London" },
  { name: "Clank! A Deck-building adventure" },
  { name: "Classic Go" },
  { name: "Clue" },
  { name: "Clue: Bob's Burger" },
  { name: "Cockroach Poker" },
  { name: "Codenames Deep Undercover" },
  { name: "Codenames Duet" },
  { name: "Codenames Pictures" },
  { name: "Codenames: Disney" },
  { name: "Codenames: Harry Potter" },
  { name: "Codenames: The Simpsons" },
  { name: "Codenmames" },
  { name: "Color Brain: Disney Edition" },
  { name: "Colt Express" },
  { name: "Concept" },
  { name: "Connect 4" },
  { name: "Coup" },
  { name: "Coup Reformation" },
  { name: "Cranium" },
  { name: "Crystal Clans" },
  { name: "Cube Quest" },
  { name: "Cyclades" },
  { name: "Dead of Winter" },
  { name: "Deadwood 1876" },
  { name: "Decrypto" },
  { name: "Descent: Journeys in the Dark" },
  { name: "Dice Forge" },
  { name: "Dice Throne Season 2 - Cursed Pirate vs Artificer" },
  { name: "Dice Throne Season 2 - Gunslinger vs Samurai" },
  { name: "Dominion" },
  { name: "Dominion 2nd Edition" },
  { name: "Dominion: Intrigue" },
  { name: "Dominoes" },
  { name: "Don't Break the Ice" },
  { name: "Down Force" },
  { name: "Dungeon Run" },
  { name: "Echo of time (Entropy Expansion)" },
  { name: "Elder Sign" },
  { name: "Elysium" },
  { name: "Entropy" },
  { name: "Everdell" },
  { name: "Exoplanets" },
  { name: "Exploding Kittens" },
  { name: "Exploding Kittens NSFW Pack" },
  { name: "Exploding Kittens Party Pack" },
  { name: "Five Tribes" },
  { name: "Flamme Rouge" },
  { name: "Flash Point: Fire Rescue" },
  { name: "Forbidden Desert" },
  { name: "Forbidden Island" },
  { name: "Formula D" },
  { name: "Fort Sumter" },
  { name: "Founders of Gloomhaven" },
  { name: "Gaia Project" },
  { name: "Get bit!" },
  { name: "Ghost Blitz" },
  { name: "Ghost Blitz 5 to 12" },
  { name: "Ghost Blitz Junior" },
  { name: "Gizmos" },
  { name: "Gobblet Gobblers" },
  { name: "Gravwell" },
  { name: "Guess Who?" },
  { name: "Guillotine" },
  { name: "Haiclue" },
  { name: "Hail Hydra" },
  { name: "Hamsterrolle" },
  { name: "Hanabi" },
  { name: "Head Hackers" },
  { name: "Hey, that's my fish!" },
  { name: "Hive" },
  { name: "Hive Carbon" },
  { name: "ICECOOL" },
  { name: "Illimat" },
  { name: "Imhotep: The Duel" },
  { name: "Incohearant" },
  { name: "Istanbul" },
  { name: "Jaipur" },
  { name: "Jamaica" },
  { name: "Jaws" },
  { name: "Kahuna 2-Player Game" },
  { name: "Keyflower" },
  { name: "Killer Bunnies" },
  { name: "King of New York" },
  { name: "King of Tokyo" },
  { name: "King of Tokyo: Dark Edition" },
  { name: "Lanterns" },
  { name: "Le Havre" },
  { name: "Legendary: A Marvel Deck-building game" },
  { name: "Lewis & Clark" },
  { name: "LINKEE" },
  { name: "Lords of Vegas" },
  { name: "Lords of Waterdeep" },
  { name: "Love letter" },
  { name: "Machi Koro" },
  { name: "Mage Wars" },
  { name: "Magic Maze" },
  { name: "Mancala" },
  { name: "Mansions of Madness" },
  { name: "Marvel Champions: The Card Game" },
  { name: "Mascarade" },
  { name: "Maskarades" },
  { name: "Mastermind" },
  { name: "Memoir 44" },
  { name: "Mice and Mystics" },
  { name: "Mille Bornes" },
  { name: "Mint Delivery" },
  { name: "Mint Works" },
  { name: "Monikers" },
  { name: "Monopoly" },
  { name: "Monopoly Deal" },
  { name: "Monopoly: California, Here we come!" },
  { name: "Monopoly: Doctor Who" },
  { name: "Monopoly: Frozen II" },
  { name: "Monopoly: Gamer" },
  { name: "Monopoly: The America" },
  { name: "Monopoly: The Walking Dead" },
  { name: "Monopoly for Milennials" },
  { name: "Munchkin" },
  { name: "Munchkin Fu" },
  { name: "Munchkin Fu" },
  { name: "Munchkin Quest" },
  { name: "Munchkin: Rick and Morty" },
  { name: "Mysterium" },
  { name: "Mythotopia" },
  { name: "New York Slice" },
  { name: "No Thanks!" },
  { name: "OK" },
  { name: "One Deck Dungeon" },
  { name: "One Night Ultimate Werewolf" },
  { name: "Operation" },
  { name: "Othello" },
  { name: "Out of the Woods" },
  { name: "Pagoda" },
  { name: "Pandemic" },
  { name: "Parcheesi: Royal edition" },
  { name: "Partners" },
  { name: "Patchwork" },
  { name: "Pictionary" },
  { name: "Pirate Fluxx" },
  { name: "PIT" },
  { name: "Point Salad" },
  { name: "Power Grid" },
  { name: "Puerto Rico" },
  { name: "Quacks of Quedlinburg" },
  { name: "Queendomino" },
  { name: "Quiddler" },
  { name: "Qwirkle" },
  { name: "Race for the Galaxy" },
  { name: "Ramen Fury" },
  { name: "Raptor" },
  { name: "Rhino Hero" },
  { name: "Rick and Morty: Total Rickall" },
  { name: "Rising Sun" },
  { name: "Risk" },
  { name: "Risk" },
  { name: "Risk Godstorm" },
  { name: "Rock & Roll Party Game" },
  { name: "Roll for the Galaxy" },
  { name: "Root" },
  { name: "Rummikub" },
  { name: "Sagrada" },
  { name: "Samurai Spirit" },
  { name: "San Juan" },
  { name: "Santorini" },
  { name: "Say Anything" },
  { name: "Say Anything" },
  { name: "Scattergories" },
  { name: "Schmovie" },
  { name: "Scotland Yard" },
  { name: "Scrabble" },
  { name: "Seasons" },
  { name: "Secret Hitler" },
  { name: "Sentinels of the Multiverse" },
  { name: "Sequence" },
  { name: "SET" },
  { name: "Settlers of Catan" },
  { name: "Sheriff of Nottingham" },
  { name: "Sketchy Stories" },
  { name: "Skull" },
  { name: "Small World" },
  { name: "Smart Ass" },
  { name: "Smash Up" },
  { name: "Sorry!" },
  { name: "Spank the Yeti" },
  { name: "Spank the Yeti: Geek Pack" },
  { name: "Spirit Island" },
  { name: "Splendor" },
  { name: "Spot it!" },
  { name: "Spot it!: Frozen II" },
  { name: "Spyfall" },
  { name: "Spyfall 2" },
  { name: "Star Fluxx" },
  { name: "Star Traders" },
  { name: "Star Trek Panic" },
  { name: "Stone Age" },
  { name: "Stop Thief!" },
  { name: "Stratego" },
  { name: "Super Hazard Quest" },
  { name: "Survive: Escape from Atlantis" },
  { name: "Sushi Go" },
  { name: "Taboo" },
  { name: "Takenoko" },
  { name: "Tara" },
  { name: "Telestrations" },
  { name: "Telestrations: After Dark" },
  { name: "Terraforming Mars" },
  { name: "Thanos Rising" },
  { name: "The Fox in The Forest" },
  { name: "The Game of Life" },
  { name: "The Great Heartland" },
  { name: "The Metagame" },
  { name: "The Mind" },
  { name: "The Mind: Extreme" },
  { name: "The Resistance" },
  { name: "The Resistance: Avalon" },
  { name: "The Werewolves of Millers Hollow" },
  { name: "The Game of Wolf" },
  { name: "Through the Desert" },
  { name: "Ticket to Ride" },
  { name: "Ticket to Ride Expansion: USA 1910" },
  { name: "Ticket to Ride: Europe" },
  { name: "Ticket to Ride: Nordic Countries" },
  { name: "Ticket to Ride: The Dice Expansion" },
  { name: "Timeline" },
  { name: "Timeline Americana" },
  { name: "Tokyo Metro" },
  { name: "Trapwords" },
  { name: "Treason in the Tower" },
  { name: "Trivial Pursuit" },
  { name: "Trouble" },
  { name: "Tsuro" },
  { name: "Twilight Struggle" },
  { name: "Unexploded cow" },
  { name: "Unlock Adventures!" },
  { name: "Uno" },
  { name: "UNO Flip" },
  { name: "UNO Frozen 2" },
  { name: "Unstable Unicorns" },
  { name: "Vault of Dragons" },
  { name: "Via Nebula" },
  { name: "Viceroy" },
  { name: "Villainous" },
  { name: "Villainous: Evil Comes Prepared" },
  { name: "Villainous: Wicked to the Core" },
  { name: "Visitor" },
  { name: "Weird Things Humans Search For" },
  { name: "Welcome to the Dungeon" },
  { name: "What Came First" },
  { name: "Wildlands" },
  { name: "Wits & Wagers" },
  { name: "Wu Wei: Journey of the Changing Path" },
  { name: "Yahtzee" },
  { name: "You Bet-Cha!" },
  { name: "Zombie Dice" },
  { name: "Zombicide" },
];
